
###
GET https://shoom-music.herokuapp.com/playlists

###
GET https://shoom-music.herokuapp.com/playlists/1


###
POST https://shoom-music.herokuapp.com/playlists
Content-Type: application/json

{
  "id": 0,
  "name": "rap"
}


###
POST https://shoom-music.herokuapp.com/playlists/add/1?trackId=1

###
DELETE https://shoom-music.herokuapp.com/playlists/remove/1?trackId=1


###
GET https://shoom-music.herokuapp.com/artists/search/gree

###
GET https://shoom-music.herokuapp.com/tracks/search/enter


###
DELETE https://shoom-music.herokuapp.com/playlists/removepl/1

###
DELETE https://shoom-music.herokuapp.com/playlists/remove/10


###
GET https://shoom-music.herokuapp.com/albums/4

###
GET https://shoom-music.herokuapp.com/albums/artist/1

###
GET https://shoom-music.herokuapp.com/artists

###
GET https://shoom-music.herokuapp.com/artists/1

###
GET https://shoom-music.herokuapp.com/genres/artists?ids=1,2

###
GET https://project-skyscanner.herokuapp.com/flights/

