
###
GET http://localhost:8080/playlists

###
GET http://localhost:8080/playlists/1


###
POST http://localhost:8080/playlists
Content-Type: application/json

{
  "id": 0,
  "name": "rock"
}

###

DELETE http://localhost:8080/playlists/delete/playlist 2

###
POST http://localhost:8080/playlists/add/1?trackId=1

###
DELETE http://localhost:8080/playlists/remove/1?trackId=1


###
GET http://localhost:8080/artists/search/gree


###
DELETE http://localhost:8080/playlists/removepl/1

